export type Category =
  | "Education & Learning Tools"
  | "Business & Strategy Tools"
  | "Marketing & SEO Tools"
  | "Sales & CRM Tools"
  | "Translation & Language Processing"
  | "Finance & Accounting Tools"
  | "Presentation & Document Generation"
  | "3D Modeling & Game Development"
  | "Security, Privacy & Compliance Tools";

export type Tag = "Enterprise-Ready" | "Free-Tier" | "Open Source" | "Automation Force Multiplier";

export type Department =
  | "Finance & Procurement"
  | "Human Resources"
  | "Mentoring & Education"
  | "Learning Content & Design"
  | "Information Technology";

export type Tool = {
  id: number;
  name: string;
  vendor?: string;
  categories: Category[];
  summary: string;
  benefits: string;
  bestFor: string;
  url: string;
  tags: Tag[];
  domain?: string;
  departments: Department[];
};

export const CATEGORIES: { key: Category; label: string; short: string }[] = [
  { key: "Education & Learning Tools", label: "Education & Learning Tools", short: "Education" },
  { key: "Business & Strategy Tools", label: "Business & Strategy Tools", short: "Business" },
  { key: "Marketing & SEO Tools", label: "Marketing & SEO Tools", short: "Marketing" },
  { key: "Sales & CRM Tools", label: "Sales & CRM Tools", short: "Sales / CRM" },
  { key: "Translation & Language Processing", label: "Translation & Language Processing", short: "Translation" },
  { key: "Finance & Accounting Tools", label: "Finance & Accounting Tools", short: "Finance" },
  { key: "Presentation & Document Generation", label: "Presentation & Document Generation", short: "Presentation" },
  { key: "3D Modeling & Game Development", label: "3D Modeling & Game Development", short: "3D / Game Dev" },
  { key: "Security, Privacy & Compliance Tools", label: "Security, Privacy & Compliance Tools", short: "Security" },
];

export const TAGS: Tag[] = ["Enterprise-Ready", "Free-Tier", "Open Source", "Automation Force Multiplier"];

export const DEPARTMENTS: Department[] = [
  "Finance & Procurement",
  "Human Resources",
  "Mentoring & Education",
  "Learning Content & Design",
  "Information Technology",
];

type Raw = Omit<Tool, "departments">;

const RAW: Raw[] = [
  // ---- Original 50 tools, re-mapped to 9 new categories ----
  { id: 1, name: "ChatGPT", vendor: "OpenAI", categories: ["Education & Learning Tools", "Business & Strategy Tools", "Presentation & Document Generation"], summary: "General-purpose assistant for writing, brainstorming, reasoning and conversational workflows.", benefits: "Highly versatile; excels at brainstorming, complex text formatting, iterative reasoning.", bestFor: "Daily knowledge work, drafting briefs and rapid problem-solving across teams.", url: "https://chat.openai.com", tags: ["Enterprise-Ready", "Free-Tier"], domain: "openai.com" },
  { id: 2, name: "Claude", vendor: "Anthropic", categories: ["Business & Strategy Tools", "Finance & Accounting Tools", "Education & Learning Tools"], summary: "Nuanced long-document analysis for legal, financial and policy material.", benefits: "Massive context window; secure, deeply analytical, human-like prose.", bestFor: "Reviewing contracts, long PDFs and producing executive-grade summaries.", url: "https://claude.ai", tags: ["Enterprise-Ready", "Free-Tier"], domain: "anthropic.com" },
  { id: 3, name: "Gemini", vendor: "Google", categories: ["Business & Strategy Tools", "Education & Learning Tools"], summary: "Multimodal reasoning over text, audio and video natively inside Google Workspace.", benefits: "Processes long video/audio native inputs effortlessly; integrates with Google Workspace.", bestFor: "Workspace-native research, meeting recaps and multimodal analysis.", url: "https://gemini.google.com", tags: ["Enterprise-Ready", "Free-Tier"], domain: "gemini.google.com" },
  { id: 4, name: "Grok", vendor: "xAI", categories: ["Business & Strategy Tools", "Marketing & SEO Tools"], summary: "Real-time conversational AI plugged into live X (Twitter) data streams.", benefits: "Accesses live, real-time data feeds via X (Twitter) for current events.", bestFor: "Live market sensing, trend tracking and social listening.", url: "https://x.ai", tags: ["Free-Tier"], domain: "x.ai" },
  { id: 5, name: "DeepSeek", categories: ["Business & Strategy Tools", "Finance & Accounting Tools"], summary: "Cost-effective open-weight LLM for text processing and reasoning.", benefits: "Publicly available model weights; slashes API costs for budget-conscious enterprises.", bestFor: "High-volume text workloads where API cost discipline matters.", url: "https://www.deepseek.com", tags: ["Open Source", "Free-Tier"], domain: "deepseek.com" },
  { id: 6, name: "Meta AI (Llama)", categories: ["Business & Strategy Tools", "Security, Privacy & Compliance Tools"], summary: "Open-source foundation model that can be self-hosted and fine-tuned.", benefits: "Allows businesses to self-host and fine-tune models locally without cloud APIs.", bestFor: "Private deployments where data must never leave the perimeter.", url: "https://ai.meta.com", tags: ["Open Source", "Enterprise-Ready"], domain: "meta.com" },
  { id: 7, name: "Jasper", categories: ["Marketing & SEO Tools"], summary: "Enterprise brand-voice copywriting and campaign generation suite.", benefits: "Built-in templates for SEO, blogs, ad copy matching unique brand tone.", bestFor: "Scaling on-brand marketing copy across channels.", url: "https://www.jasper.ai", tags: ["Enterprise-Ready"], domain: "jasper.ai" },
  { id: 8, name: "Copy.ai", categories: ["Marketing & SEO Tools", "Sales & CRM Tools"], summary: "Go-to-market and sales copy automation workflows.", benefits: "Streamlines marketing workflows, bulk email drafting, social media pipelines.", bestFor: "Outbound email, social posts and GTM content pipelines.", url: "https://www.copy.ai", tags: ["Free-Tier", "Automation Force Multiplier"], domain: "copy.ai" },
  { id: 9, name: "Writer", categories: ["Marketing & SEO Tools", "Business & Strategy Tools"], summary: "Enterprise generative content engine for regulated industries.", benefits: "Enforces corporate compliance, editorial style guides, data privacy standards out of the box.", bestFor: "Regulated industries needing compliant on-brand content at scale.", url: "https://writer.com", tags: ["Enterprise-Ready"], domain: "writer.com" },
  { id: 10, name: "Anyword", categories: ["Marketing & SEO Tools"], summary: "Predictive copy optimization with conversion scoring before publish.", benefits: "Uses predictive performance scores to forecast conversions before publishing.", bestFor: "Performance marketers iterating on ad and landing-page copy.", url: "https://anyword.com", tags: ["Enterprise-Ready"], domain: "anyword.com" },

  { id: 11, name: "GitHub Copilot", categories: ["Business & Strategy Tools", "Security, Privacy & Compliance Tools"], summary: "In-line code completion and multi-file refactoring inside the IDE.", benefits: "Speeds up development by predicting code blocks directly inside the IDE.", bestFor: "Accelerating day-to-day engineering productivity.", url: "https://github.com/features/copilot", tags: ["Enterprise-Ready"], domain: "github.com" },
  { id: 12, name: "Cursor", categories: ["Business & Strategy Tools"], summary: "AI-first code editor with repository-wide reasoning and chat.", benefits: "Chat directly with entire codebase, generating complex features autonomously.", bestFor: "Senior engineers shipping complex features across large codebases.", url: "https://cursor.com", tags: ["Enterprise-Ready", "Automation Force Multiplier"], domain: "cursor.com" },
  { id: 13, name: "v0", vendor: "Vercel", categories: ["Presentation & Document Generation", "Business & Strategy Tools"], summary: "Frontend UI generator producing React + Tailwind from prompts.", benefits: "Generates production-ready React, Tailwind CSS, and HTML code from simple UI descriptions.", bestFor: "Rapid UI prototypes and design-to-code handoffs.", url: "https://v0.dev", tags: ["Free-Tier"], domain: "v0.dev" },
  { id: 14, name: "Lovable", categories: ["Business & Strategy Tools", "Presentation & Document Generation"], summary: "Full-stack web app generator powered by natural language.", benefits: "Builds operational web apps from natural language, handling front-to-back engineering logic.", bestFor: "Non-engineers shipping real internal tools and prototypes.", url: "https://lovable.dev", tags: ["Free-Tier", "Automation Force Multiplier"], domain: "lovable.dev" },
  { id: 15, name: "Claude Code", categories: ["Business & Strategy Tools", "Security, Privacy & Compliance Tools"], summary: "Terminal-native agentic programming and deep debugging.", benefits: "Executes tasks inside developer CLI, managing local testing and repo refactoring.", bestFor: "Power users automating CLI workflows and code triage.", url: "https://claude.com/product/claude-code", tags: ["Enterprise-Ready"], domain: "anthropic.com" },
  { id: 16, name: "Anvil", categories: ["Business & Strategy Tools"], summary: "Rapid Python full-stack web app development platform.", benefits: "Permits building complete, database-backed web applications entirely using Python code.", bestFor: "Python teams building internal apps without learning JS.", url: "https://anvil.works", tags: ["Free-Tier"], domain: "anvil.works" },
  { id: 17, name: "Tabnine", categories: ["Security, Privacy & Compliance Tools", "Business & Strategy Tools"], summary: "Private, locally hosted code auto-completion.", benefits: "Offers locally hostable AI models ensuring corporate codebases never leave local environments.", bestFor: "Security-sensitive engineering orgs requiring on-prem AI.", url: "https://www.tabnine.com", tags: ["Enterprise-Ready", "Open Source"], domain: "tabnine.com" },
  { id: 18, name: "Codeium", categories: ["Business & Strategy Tools"], summary: "Free, fast multi-IDE code acceleration.", benefits: "Provides lightning-fast suggestions/chat compatible with over 40+ popular IDEs.", bestFor: "Indie devs and small teams wanting Copilot-like speed for free.", url: "https://codeium.com", tags: ["Free-Tier"], domain: "codeium.com" },
  { id: 19, name: "Replit Agent", categories: ["Business & Strategy Tools", "Presentation & Document Generation"], summary: "Cloud agent that builds, deploys and provisions databases from prompts.", benefits: "Builds, provisions databases, and deploys applications to live URLs automatically from prompts.", bestFor: "Spinning up working prototypes in minutes from a single prompt.", url: "https://replit.com", tags: ["Free-Tier", "Automation Force Multiplier"], domain: "replit.com" },
  { id: 20, name: "Amazon Q", categories: ["Business & Strategy Tools", "Security, Privacy & Compliance Tools"], summary: "AWS-native assistant for infrastructure, security and cost optimization.", benefits: "Explains AWS configurations, assists with security audits, optimizes cloud resource costs.", bestFor: "AWS-heavy orgs tuning security and cloud spend.", url: "https://aws.amazon.com/q/", tags: ["Enterprise-Ready", "Automation Force Multiplier"], domain: "aws.amazon.com" },

  { id: 21, name: "Perplexity AI", categories: ["Education & Learning Tools", "Business & Strategy Tools"], summary: "Conversational web search with inline source citations.", benefits: "Delivers direct answers compiled from live web sources with inline verification citations.", bestFor: "Fact-grounded research with traceable citations.", url: "https://www.perplexity.ai", tags: ["Free-Tier", "Enterprise-Ready"], domain: "perplexity.ai" },
  { id: 22, name: "NotebookLM", vendor: "Google", categories: ["Education & Learning Tools", "Presentation & Document Generation"], summary: "Source-grounded synthesis turning your documents into study guides and audio briefs.", benefits: "Generates instant study guides, summaries, interactive audio briefs strictly from uploaded documents.", bestFor: "Onboarding new hires and turning long docs into digestible briefs.", url: "https://notebooklm.google.com", tags: ["Free-Tier", "Enterprise-Ready", "Automation Force Multiplier"], domain: "notebooklm.google.com" },
  { id: 23, name: "Consensus", categories: ["Education & Learning Tools"], summary: "Evidence-based scientific search across peer-reviewed papers.", benefits: "Searches peer-reviewed papers to provide data-backed answers to health/science queries.", bestFor: "Educators and researchers needing peer-reviewed evidence.", url: "https://consensus.app", tags: ["Free-Tier"], domain: "consensus.app" },
  { id: 24, name: "Elicit", categories: ["Education & Learning Tools"], summary: "Literature review automation that extracts findings from thousands of papers.", benefits: "Extracts data tables, findings, concepts across thousands of academic papers simultaneously.", bestFor: "Literature reviews and academic synthesis at scale.", url: "https://elicit.com", tags: ["Free-Tier", "Automation Force Multiplier"], domain: "elicit.com" },
  { id: 25, name: "Komo", categories: ["Education & Learning Tools"], summary: "Ad-free conceptual web exploration designed for deep dives.", benefits: "Organizes search journeys into conversational, deep-dive modules rather than blue links.", bestFor: "Exploratory research without ad-driven noise.", url: "https://komo.ai", tags: ["Free-Tier"], domain: "komo.ai" },

  { id: 26, name: "Midjourney", categories: ["Marketing & SEO Tools", "Presentation & Document Generation"], summary: "Industry-leading cinematic image generation.", benefits: "Industry-leading artistic quality, rendering complex textures and atmospheric lighting.", bestFor: "Hero imagery, brand visuals and editorial-grade artwork.", url: "https://www.midjourney.com", tags: ["Enterprise-Ready"], domain: "midjourney.com" },
  { id: 27, name: "DALL-E 3", vendor: "OpenAI", categories: ["Marketing & SEO Tools", "Education & Learning Tools"], summary: "Precise prompt-driven image generation inside ChatGPT.", benefits: "Understands complex text instructions precisely inside the ChatGPT ecosystem.", bestFor: "Illustrating concepts, textbook visuals and diagrammatic art.", url: "https://openai.com/dall-e-3", tags: ["Enterprise-Ready"], domain: "openai.com" },
  { id: 28, name: "Stable Diffusion", categories: ["Marketing & SEO Tools", "3D Modeling & Game Development"], summary: "Open-source, customizable image diffusion engine.", benefits: "Offers complete control via local installation, custom checkpoints, plugin extensions.", bestFor: "Custom pipelines and game-asset art generation.", url: "https://stability.ai", tags: ["Open Source", "Free-Tier"], domain: "stability.ai" },
  { id: 29, name: "Canva Magic Studio", categories: ["Presentation & Document Generation", "Marketing & SEO Tools"], summary: "AI-powered graphic design for social, decks and assets.", benefits: "Lowers barrier to entry for editing objects, text effects, and reshaping design elements.", bestFor: "Non-designers producing on-brand visuals fast.", url: "https://www.canva.com", tags: ["Free-Tier", "Enterprise-Ready"], domain: "canva.com" },
  { id: 30, name: "Adobe Firefly", categories: ["Marketing & SEO Tools", "Presentation & Document Generation"], summary: "Commercially safe generative imagery trained on licensed data.", benefits: "Trained exclusively on licensed/public domain images, ensuring corporate legal safety.", bestFor: "Brand-safe image generation for enterprise marketing.", url: "https://www.adobe.com/products/firefly.html", tags: ["Enterprise-Ready"], domain: "adobe.com" },
  { id: 31, name: "Google Pics", categories: ["Presentation & Document Generation", "Marketing & SEO Tools"], summary: "Workspace canvas image generation embedded in Slides and Drive.", benefits: "Allows collaborative canvases and instant image generation embedded within Slides/Drive.", bestFor: "Inline visuals while collaborating in Workspace.", url: "https://workspace.google.com", tags: ["Enterprise-Ready"], domain: "google.com" },

  { id: 32, name: "HeyGen", categories: ["Education & Learning Tools", "Marketing & SEO Tools"], summary: "Synthetic AI avatars with multilingual lip-synced video.", benefits: "Generates realistic, multilingual corporate videos using 15-second training clips and flawless lip-syncing.", bestFor: "Localized training videos and avatar-led corporate communications.", url: "https://www.heygen.com", tags: ["Enterprise-Ready", "Automation Force Multiplier"], domain: "heygen.com" },
  { id: 33, name: "Runway (Gen-3)", categories: ["Marketing & SEO Tools", "3D Modeling & Game Development"], summary: "Photorealistic AI video generation with cinematic motion controls.", benefits: "Controls camera panning, text-to-video motion dynamics, environmental physics.", bestFor: "Cinematic short-form brand and concept video.", url: "https://runwayml.com", tags: ["Enterprise-Ready"], domain: "runwayml.com" },
  { id: 34, name: "ElevenLabs", categories: ["Education & Learning Tools", "Marketing & SEO Tools"], summary: "Hyper-realistic text-to-speech and multilingual voice cloning.", benefits: "Captures human emotional nuances, pacing, inflections across dozens of languages.", bestFor: "Voiceovers for courses, ads and audiobooks.", url: "https://elevenlabs.io", tags: ["Enterprise-Ready", "Free-Tier"], domain: "elevenlabs.io" },
  { id: 35, name: "Sora", vendor: "OpenAI", categories: ["Marketing & SEO Tools", "3D Modeling & Game Development"], summary: "Long-horizon text-to-video with coherent physics.", benefits: "Creates detailed scenes with multiple characters and complex motions up to a minute long.", bestFor: "Concept films and storyboard-to-video exploration.", url: "https://openai.com/sora", tags: ["Enterprise-Ready"], domain: "openai.com" },
  { id: 36, name: "Descript", categories: ["Education & Learning Tools", "Presentation & Document Generation"], summary: "Edit audio and video by editing transcript text.", benefits: "Edit video simply by deleting words from transcribed text; includes voice correction.", bestFor: "Podcasts, training videos and post-production cleanup.", url: "https://www.descript.com", tags: ["Free-Tier", "Automation Force Multiplier"], domain: "descript.com" },
  { id: 37, name: "Stability Audio", categories: ["Marketing & SEO Tools"], summary: "Structured AI music and sound-effect composition.", benefits: "Generates coherent multi-minute music tracks and sound effects via open-weight options.", bestFor: "Royalty-free music for video, ads and games.", url: "https://stability.ai/stable-audio", tags: ["Open Source"], domain: "stability.ai" },
  { id: 38, name: "Suno AI", categories: ["Marketing & SEO Tools"], summary: "Generate full vocal songs with lyrics and instrumentation.", benefits: "Produces radio-ready songs complete with custom instrumentation, lyrics, and vocal harmonies.", bestFor: "Jingles, brand anthems and creative campaigns.", url: "https://suno.com", tags: ["Free-Tier"], domain: "suno.com" },
  { id: 39, name: "Lovo.ai", categories: ["Education & Learning Tools", "Marketing & SEO Tools"], summary: "Professional voiceovers for marketing and e-learning.", benefits: "Offers extensive library of specialized character voices engineered for long-form audiobooks.", bestFor: "Long-form course narration and ad voicework.", url: "https://lovo.ai", tags: ["Free-Tier", "Enterprise-Ready"], domain: "lovo.ai" },

  { id: 40, name: "n8n", categories: ["Business & Strategy Tools", "Security, Privacy & Compliance Tools"], summary: "Fair-code workflow automation with deep API and code support.", benefits: "Connects complex APIs visually; allows custom JavaScript/Python injections. Secure and self-hostable.", bestFor: "Self-hosted automation across complex enterprise stacks.", url: "https://n8n.io", tags: ["Open Source", "Enterprise-Ready", "Automation Force Multiplier"], domain: "n8n.io" },
  { id: 41, name: "Zapier Agents", categories: ["Business & Strategy Tools", "Sales & CRM Tools"], summary: "AI agents orchestrating thousands of SaaS apps.", benefits: "Connects to thousands of standard SaaS apps instantly; monitors queues to make autonomous decisions.", bestFor: "Cross-SaaS automation with minimal engineering.", url: "https://zapier.com/agents", tags: ["Enterprise-Ready", "Automation Force Multiplier"], domain: "zapier.com" },
  { id: 42, name: "Gamma", categories: ["Presentation & Document Generation"], summary: "Generate presentations, webpages and docs from prompts.", benefits: "Eliminates manual slide-building by arranging text prompts into visually stunning pitch decks.", bestFor: "Pitch decks and internal briefs in minutes.", url: "https://gamma.app", tags: ["Free-Tier"], domain: "gamma.app" },
  { id: 43, name: "Gumloop", categories: ["Business & Strategy Tools"], summary: "Visual builder for multi-step scraping and data pipelines.", benefits: "Grants ability to construct powerful background AI scrapers and data parsers visually.", bestFor: "Background scrapers and data-parsing pipelines.", url: "https://www.gumloop.com", tags: ["Enterprise-Ready", "Automation Force Multiplier"], domain: "gumloop.com" },
  { id: 44, name: "Otter.ai", categories: ["Business & Strategy Tools", "Education & Learning Tools"], summary: "Live meeting transcription with speaker labels and action items.", benefits: "Listens to live calls, attributes speakers, and extracts post-meeting to-do lists.", bestFor: "Capturing meeting notes and follow-ups automatically.", url: "https://otter.ai", tags: ["Free-Tier", "Enterprise-Ready"], domain: "otter.ai" },
  { id: 45, name: "Beautiful.ai", categories: ["Presentation & Document Generation"], summary: "Smart presentation layouts that auto-adjust as you type.", benefits: "Automatically resizes layouts and shifts iconography when you type text for consistent rules.", bestFor: "Consistent on-brand decks across teams.", url: "https://www.beautiful.ai", tags: ["Enterprise-Ready"], domain: "beautiful.ai" },
  { id: 46, name: "Botpress", categories: ["Sales & CRM Tools", "Business & Strategy Tools"], summary: "Multi-channel conversational chatbot platform.", benefits: "Integrates deep customer support workflows across WhatsApp, Telegram, and websites.", bestFor: "Customer support bots across WhatsApp, web and Telegram.", url: "https://botpress.com", tags: ["Open Source", "Enterprise-Ready", "Automation Force Multiplier"], domain: "botpress.com" },
  { id: 47, name: "Clearscope", categories: ["Marketing & SEO Tools"], summary: "SEO content optimization with keyword and SERP analysis.", benefits: "Deciphers search engine patterns to map keywords needed to rank on Google.", bestFor: "On-page SEO optimization for editorial teams.", url: "https://www.clearscope.io", tags: ["Enterprise-Ready"], domain: "clearscope.io" },
  { id: 48, name: "Originality.ai", categories: ["Marketing & SEO Tools", "Security, Privacy & Compliance Tools"], summary: "AI-content detection and plagiarism auditing.", benefits: "Empowers publishers to verify if web copy was written by humans or generated by an LLM.", bestFor: "Editorial integrity audits and publisher compliance.", url: "https://originality.ai", tags: ["Enterprise-Ready"], domain: "originality.ai" },
  { id: 49, name: "Fireflies.ai", categories: ["Business & Strategy Tools", "Sales & CRM Tools"], summary: "Voice analytics and central meeting intelligence repository.", benefits: "Transcribes internal meetings while tracking overall speaker sentiment and target keywords.", bestFor: "Sales call coaching and meeting intelligence.", url: "https://fireflies.ai", tags: ["Enterprise-Ready", "Automation Force Multiplier"], domain: "fireflies.ai" },
  { id: 50, name: "Feedly Leo", categories: ["Business & Strategy Tools", "Marketing & SEO Tools"], summary: "Enterprise market intelligence and AI news curation.", benefits: "Filters noise by teaching an AI assistant to curate daily news tied to competitors.", bestFor: "Competitive monitoring and curated industry news.", url: "https://feedly.com", tags: ["Enterprise-Ready"], domain: "feedly.com" },

  // ---- New tools 51-70 ----
  { id: 51, name: "HubSpot AI", categories: ["Sales & CRM Tools"], summary: "Smart inbound sales, lead routing, and customer pipeline management dashboard.", benefits: "Speeds up email outreach response, optimizes customer response scoring.", bestFor: "Automating client relationship management and email triage.", url: "https://www.hubspot.com", tags: ["Enterprise-Ready"], domain: "hubspot.com" },
  { id: 52, name: "Salesforce Einstein", categories: ["Sales & CRM Tools"], summary: "Enterprise predictive analytics and customer interaction tracking.", benefits: "Anticipates customer purchase cycles and updates internal metrics automatically.", bestFor: "Large-scale business pipeline projections.", url: "https://www.salesforce.com", tags: ["Enterprise-Ready"], domain: "salesforce.com" },
  { id: 53, name: "Gong.io", categories: ["Sales & CRM Tools"], summary: "Operational conversation intelligence engine capturing sales calls.", benefits: "Analyzes internal verbal customer patterns and outlines explicit action pipelines.", bestFor: "Training remote account management teams.", url: "https://www.gong.io", tags: ["Enterprise-Ready"], domain: "gong.io" },
  { id: 54, name: "DeepL Pro", categories: ["Translation & Language Processing"], summary: "Precise enterprise document translation preserving corporate formatting layout.", benefits: "Drastically cuts turnaround for local language adaptations.", bestFor: "Multi-language educational curriculum translation.", url: "https://www.deepl.com", tags: ["Enterprise-Ready"], domain: "deepl.com" },
  { id: 55, name: "Grammarly Enterprise", categories: ["Translation & Language Processing"], summary: "Real-time grammar auditing, structural adjustment, and tone verification.", benefits: "Assures strict compliance across all outgoing communication.", bestFor: "Corporate document writing and report compilation.", url: "https://www.grammarly.com", tags: ["Enterprise-Ready"], domain: "grammarly.com" },
  { id: 56, name: "QuillBot", categories: ["Translation & Language Processing"], summary: "Advanced multi-mode sentence restructuring and content summarization framework.", benefits: "Speeds up article synthesis and content variations.", bestFor: "Educational content editing and manual rewrites.", url: "https://quillbot.com", tags: ["Free-Tier"], domain: "quillbot.com" },
  { id: 57, name: "QuickBooks Advanced AI", categories: ["Finance & Accounting Tools"], summary: "Automated cash flow mapping, tax categorization, and anomaly detection.", benefits: "Identifies bookkeeping issues before quarterly reviews.", bestFor: "Small to mid-scale financial ledger maintenance.", url: "https://quickbooks.intuit.com", tags: ["Enterprise-Ready"], domain: "quickbooks.intuit.com" },
  { id: 58, name: "Xero Analytics", categories: ["Finance & Accounting Tools"], summary: "Predictive banking reconciliation and cloud invoice processing.", benefits: "Eradicates manual cross-referencing on high-volume accounts.", bestFor: "Financial cash forecasting and automatic matching.", url: "https://www.xero.com", tags: ["Enterprise-Ready"], domain: "xero.com" },
  { id: 59, name: "Ramp", categories: ["Finance & Accounting Tools"], summary: "Smart corporate expense scanning and spend control platform.", benefits: "Instantly detects policy violations on submitted receipts.", bestFor: "Operational cost monitoring and employee reimbursements.", url: "https://www.ramp.com", tags: ["Enterprise-Ready"], domain: "ramp.com" },
  { id: 60, name: "Tome", categories: ["Presentation & Document Generation"], summary: "Rapid text-to-presentation generator laying out interactive canvas slides.", benefits: "Formats content into complete presentations in moments.", bestFor: "Quick internal concept pitches and slide outlines.", url: "https://tome.app", tags: ["Free-Tier"], domain: "tome.app" },
  { id: 61, name: "Mentimeter", categories: ["Education & Learning Tools"], summary: "Interactive classroom and lecture polling framework with dynamic charts.", benefits: "Heightens student attention span during live training calls.", bestFor: "Dynamic remote learning engagement.", url: "https://www.mentimeter.com", tags: ["Enterprise-Ready"], domain: "mentimeter.com" },
  { id: 62, name: "Coursera Course Builder", categories: ["Education & Learning Tools"], summary: "Enterprise tool organizing skill paths and standard operating procedures.", benefits: "Recommends specialized tracks based on internal career goals.", bestFor: "Structured employee upskilling and skills tracking.", url: "https://www.coursera.org", tags: ["Enterprise-Ready"], domain: "coursera.org" },
  { id: 63, name: "EdApp", categories: ["Education & Learning Tools"], summary: "Microlearning management platform featuring built-in templates.", benefits: "Converts long PDFs into interactive, bite-sized lessons in seconds.", bestFor: "Mobile-first corporate onboarding.", url: "https://www.edapp.com", tags: ["Enterprise-Ready", "Free-Tier"], domain: "edapp.com" },
  { id: 64, name: "Spline 3D", categories: ["3D Modeling & Game Development"], summary: "Web-based real-time 3D web asset design and vector canvas system.", benefits: "Generates interactive graphics natively compatible with standard browsers.", bestFor: "Creative digital content production.", url: "https://spline.design", tags: ["Free-Tier"], domain: "spline.design" },
  { id: 65, name: "Unity Muse", categories: ["3D Modeling & Game Development"], summary: "Text-to-texture and agent animation framework for game building.", benefits: "Drastically cuts down asset prototyping timeline.", bestFor: "Immersive learning simulations and virtual reality environments.", url: "https://unity.com", tags: ["Enterprise-Ready"], domain: "unity.com" },
  { id: 66, name: "Unreal Engine Sky", categories: ["3D Modeling & Game Development"], summary: "Scalable environment creation helper and landscape generation engine.", benefits: "Builds hyper-realistic backdrops using plain text descriptions.", bestFor: "Cinematic rendering and simulation builds.", url: "https://www.unrealengine.com", tags: ["Enterprise-Ready"], domain: "unrealengine.com" },
  { id: 67, name: "OneTrust", categories: ["Security, Privacy & Compliance Tools"], summary: "Automated data governance, POPIA/GDPR framework checking, and privacy risk tracking.", benefits: "Identifies hidden security gaps in SaaS application data workflows.", bestFor: "Strict corporate compliance audits.", url: "https://www.onetrust.com", tags: ["Enterprise-Ready"], domain: "onetrust.com" },
  { id: 68, name: "Darktrace", categories: ["Security, Privacy & Compliance Tools"], summary: "Self-learning system network monitoring flagging anomalies in real-time.", benefits: "Halts internal data leaks and external threats as they occur.", bestFor: "IT network defense and perimeter protection.", url: "https://www.darktrace.com", tags: ["Enterprise-Ready"], domain: "darktrace.com" },
  { id: 69, name: "Snyk", categories: ["Security, Privacy & Compliance Tools"], summary: "Developer-first security scanning testing open-source code libraries for errors.", benefits: "Pinpoints vulnerabilities directly inside codebases during staging.", bestFor: "Secure deployment checking in software pipelines.", url: "https://snyk.io", tags: ["Enterprise-Ready"], domain: "snyk.io" },
  { id: 70, name: "AlphaSense", categories: ["Business & Strategy Tools"], summary: "High-speed market intelligence indexing public financial filings and trend data.", benefits: "Surfaces competitor data and industry changes instantly.", bestFor: "Executive strategy decision-making.", url: "https://www.alpha-sense.com", tags: ["Enterprise-Ready"], domain: "alpha-sense.com" },
];

const DEPT_MAP: Record<Department, string[]> = {
  "Finance & Procurement": ["DeepSeek", "Claude", "Amazon Q", "Anyword", "Clearscope", "Perplexity AI", "Otter.ai", "Fireflies.ai", "QuickBooks Advanced AI", "Xero Analytics", "Ramp", "AlphaSense"],
  "Human Resources": ["Writer", "Copy.ai", "Originality.ai", "Jasper", "Otter.ai", "HeyGen", "ChatGPT", "Gemini", "Grammarly Enterprise", "Coursera Course Builder", "EdApp"],
  "Mentoring & Education": ["NotebookLM", "Gamma", "Beautiful.ai", "Consensus", "Elicit", "Claude", "ChatGPT", "Perplexity AI", "ElevenLabs", "Mentimeter", "Coursera Course Builder", "EdApp", "DeepL Pro", "QuillBot"],
  "Learning Content & Design": ["Midjourney", "Adobe Firefly", "Canva Magic Studio", "HeyGen", "ElevenLabs", "DALL-E 3", "Runway (Gen-3)", "Suno AI", "Lovo.ai", "Descript", "Sora", "Stable Diffusion", "Stability Audio", "Google Pics", "Gamma", "Tome", "Spline 3D", "Unity Muse", "Unreal Engine Sky"],
  "Information Technology": ["GitHub Copilot", "Cursor", "v0", "Lovable", "Replit Agent", "Tabnine", "Codeium", "Claude Code", "Anvil", "n8n", "Botpress", "Amazon Q", "Gumloop", "Zapier Agents", "OneTrust", "Darktrace", "Snyk"],
};

function deptsFor(name: string): Department[] {
  return DEPARTMENTS.filter(d => DEPT_MAP[d].includes(name));
}

export const TOOLS: Tool[] = RAW.map(r => ({ ...r, departments: deptsFor(r.name) }));

export const ENTERPRISE_HIGHLIGHTS = new Set([
  "n8n", "Zapier Agents", "Gumloop", "Botpress", "Fireflies.ai", "Cursor", "Amazon Q", "Writer", "NotebookLM",
  "HubSpot AI", "Salesforce Einstein", "Darktrace", "OneTrust",
]);

export const TRENDING = ["ChatGPT", "Claude", "Cursor", "n8n", "Midjourney", "NotebookLM", "Lovable", "HeyGen", "HubSpot AI", "DeepL Pro", "Tome", "Spline 3D"];

export function logoUrl(tool: Tool): string | null {
  if (!tool.domain) return null;
  return `https://www.google.com/s2/favicons?domain=${tool.domain}&sz=128`;
}

// LinkedIn-style feed posts for Trends page
export type FeedPost = {
  id: number;
  author: string;
  role: string;
  org: string;
  time: string;
  body: string;
  topic: string;
  reactions: number;
  comments: number;
};

export const FEED_POSTS: FeedPost[] = [
  { id: 1, author: "Lerato Mokoena", role: "Head of Digital Transformation", org: "eSTUDY South Africa", time: "2h", topic: "Workflow Automation", body: "Just rolled out n8n + Zapier Agents across our HR onboarding pipeline. Average ticket resolution dropped from 3 days to 4 hours. The era of manual coordination is officially over for our team. 🔥", reactions: 248, comments: 31 },
  { id: 2, author: "Sipho Dlamini", role: "AI Research Lead", org: "AI Think Tank", time: "5h", topic: "LLMs", body: "Claude 4 just shipped extended-context coding mode — we benchmarked it against GPT-5 on 12 internal refactor tasks. Claude won 9 of 12 on long-file accuracy. Worth a pilot if you're shipping enterprise codebases.", reactions: 412, comments: 58 },
  { id: 3, author: "Naledi van der Merwe", role: "Learning Experience Designer", org: "eSTUDY South Africa", time: "8h", topic: "EdTech", body: "HeyGen avatars now support 13 South African accents natively, including isiZulu and Afrikaans. Massive unlock for local corporate training content. Built a 40-min compliance course in under a day.", reactions: 186, comments: 22 },
  { id: 4, author: "Themba Khumalo", role: "CFO", org: "Nexus Holdings", time: "1d", topic: "FinTech", body: "Ramp + QuickBooks AI integration eliminated 80% of our manual expense reconciliation last quarter. Policy violations get flagged before they hit the ledger. Finance teams should be evaluating this seriously.", reactions: 521, comments: 73 },
  { id: 5, author: "Ayesha Pillay", role: "Senior Engineer", org: "ZA Cloud Co.", time: "1d", topic: "Developer Tools", body: "Cursor's repository-wide agent shipped a feature for me overnight while I slept. Full PR, tests passing, types clean. We're entering a strange new era of asynchronous engineering.", reactions: 894, comments: 142 },
  { id: 6, author: "Marcus Chen", role: "VP Marketing", org: "Velocity Brands", time: "2d", topic: "Marketing", body: "Used Jasper + Anyword to A/B test 60 ad variants in one afternoon. Top performer beat our human-written control by 38% CTR. Predictive scoring is no longer a 'maybe' — it's table stakes.", reactions: 367, comments: 41 },
  { id: 7, author: "Katlego Mahlangu", role: "Compliance Officer", org: "eSTUDY South Africa", time: "2d", topic: "Privacy & Compliance", body: "OneTrust caught a POPIA gap in one of our learning sub-processors last week. Automated governance is no longer a nice-to-have for South African enterprises — it's mission-critical.", reactions: 203, comments: 18 },
  { id: 8, author: "Rachel O'Connor", role: "Product Lead", org: "Spline.design", time: "3d", topic: "3D & XR", body: "Spline now generates fully interactive 3D web scenes from a single image input. Game studios and product designers should be paying attention — the prototyping moat just collapsed.", reactions: 478, comments: 67 },
  { id: 9, author: "Jamal Reddy", role: "Head of Sales", org: "Catalyst CRM", time: "3d", topic: "Sales & CRM", body: "Gong.io flagged that our top-performing reps say the phrase 'let me show you' 4x more than average closers. Tiny patterns, massive revenue implications. Sales coaching will never be guesswork again.", reactions: 612, comments: 89 },
  { id: 10, author: "Priya Ramcharan", role: "Director of L&D", org: "Pan-African Skills Council", time: "4d", topic: "EdTech", body: "Mentimeter + ElevenLabs in one workshop = 94% engagement scores across 200 remote learners. Voice and interaction are the next frontier of learning design.", reactions: 289, comments: 35 },
  { id: 11, author: "Bongani Sithole", role: "Founder", org: "AI Think Tank", time: "5d", topic: "Industry Trends", body: "Just published our 2026 South African AI Readiness Index. TL;DR: 71% of mid-market firms are piloting AI, but only 18% have governance frameworks in place. The talent gap is widening fast.", reactions: 1024, comments: 187 },
  { id: 12, author: "Sara Lindgren", role: "Localization Strategist", org: "DeepL", time: "6d", topic: "Translation", body: "DeepL Pro now handles 33 languages with layout-preserving PDF translation. African language coverage is growing — Swahili and Zulu in private beta. Big step for content sovereignty.", reactions: 156, comments: 24 },
  { id: 13, author: "Lesedi Nkosi", role: "Operations Director", org: "eSTUDY South Africa", time: "1w", topic: "Workflow Automation", body: "Built an end-to-end compliance reporting workflow with Gumloop scraping regulator updates, Claude summarizing them, and Fireflies briefing our exec team. Zero human input after setup. The future is here.", reactions: 723, comments: 102 },
  { id: 14, author: "David Park", role: "Security Architect", org: "Sentinel Systems", time: "1w", topic: "Cybersecurity", body: "Darktrace caught a credential-stuffing attempt on our edge in under 90 seconds last Tuesday. Self-learning network defense is no longer aspirational — it's operational reality.", reactions: 388, comments: 47 },
  { id: 15, author: "Aisha Bello", role: "Strategy Consultant", org: "AlphaSense Partners", time: "2w", topic: "Market Intelligence", body: "AlphaSense surfaced an earnings-call signal from a competitor that translated into a R12M strategic pivot for one of our clients. Curated intelligence at machine speed is the new executive edge.", reactions: 445, comments: 56 },
];
